### ISSUE TITLE
convert xml failed

### ISSUE THREAD

**Issue by duqiyao** [KennthShang/PhaBOX#1]
Hello, teacher, when I run the GitHub command, the following error occurs and I can't find the relevant solution on the Internet, so please help to check it, thank you
nohup python /data/software/PhaBOX-main/main.py --contigs final-viral-combined-for-dramv.fa --threads 8 --len 1000 --rootpth simple_test --out out/ --dbdir database/ --parampth parameters/ &

blastxml_to_tabular.py -o simple_test/midfolder//phamer_results.tab -c qseqid,sseqid,pident,length,mismatch,gapopen,qstart,qend,sstart,send,evalue simple_test/midfolder//phamer_results.xml
convert xml failed

**Comment by KennthShang** [comment]
Did you follow the guidelines and place the file into the right place:

```
# move the script to where the conda located
cp blastxml_to_tabular.py {path_to_conda}/envs/phabox/bin/blastxml_to_tabular.py
chmod 777 {path_to_conda}/envs/phabox/bin/blastxml_to_tabular.py
```

you can try to run the command below:
```
blastxml_to_tabular.py
```
to see whether the python script is executable.

**Comment by duqiyao** [comment]
Thanks for the teacher's quick reply. The annotation has been successfully modified. Thank you very much




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KennthShang/PhaBOX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月15日(星期三) 上午9:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KennthShang/PhaBOX] convert xml failed (Issue #1)





 
Did you follow the guidelines and place the file into the right place:
 # move the script to where the conda located cp blastxml_to_tabular.py {path_to_conda}/envs/phabox/bin/blastxml_to_tabular.py chmod 777 {path_to_conda}/envs/phabox/bin/blastxml_to_tabular.py  
you can try to run the command below:
 blastxml_to_tabular.py  
to see whether the python script is executable.

**Comment by KennthShang** [comment]
good to know
