### ISSUE TITLE
device.type == "cpu"

### ISSUE THREAD

**Issue by Microbion** [KennthShang/PhaBOX#10]
![image](https://github.com/KennthShang/PhaBOX/assets/35793183/646f214b-ecbc-4514-abaa-78b38da636eb)
It seems like that device == "cpu" doesn't work. I build the phabox environment with the command `conda env create -f webserver.yml -n phabox`, and pytorch version is 1.10.1.

**Comment by KennthShang** [comment]
What do you mean device == "cpu" doesn't work. Line 75 will check whether there is a GPU available. If yes, the device will be cuda. If you only want to use CPU, you can set Line 75 as device="cpu"

**Comment by Microbion** [comment]
I mean is this a bug? "If" expression in line 76 returns False in my phabox environment unexpectely.
![image](https://github.com/KennthShang/PhaBOX/assets/35793183/4cebbafa-c3a9-46c0-a2ea-700375fc4dac)

**Comment by KennthShang** [comment]
I got what you mean. It is indeed a bug, and it was fixed in the latest version. Thanks for your report

**Comment by Microbion** [comment]
Tanks for your prompt reply
