### ISSUE TITLE
phagcn_prediction.csv not created in midfolder

### ISSUE THREAD

**Issue by sydelstan** [KennthShang/PhaBOX#15]
Hello,

I have a confusing error where the program seems to run fine but it produces an error that says "FileNotFoundError: [Errno 2] No such file or directory: '/midfolder//phagcn_prediction.csv'. All of the CSV files seem to be generated okay in the out folder, even tho phatyp_prediction.csv produces a file that lists a phage in a contig that has a score of 0 in the phagcn_prediction.csv file

**Comment by KennthShang** [comment]
Hi there,

Since It is the first time I have seen this problem. Maybe you can try to run it again? Or if the data is not too large, maybe you can send it to me via email.

Also, you can check whether is a disk usage problem

Best,
Jiayu

**Comment by sydelstan** [comment]
Okay, I will send an email

**Comment by KennthShang** [comment]
Hi there,

The PhaBOX is upgraded to a 2.0 version with more powerful usage. Besides, it can handle all kinds of viruses now. Feel free to check!

Best,
Jiayu
