### ISSUE TITLE
Dependency issue with mamba/conda installation

### ISSUE THREAD

**Issue by sulmanm1** [KennthShang/PhaBOX#17]
Thank you for this great tool. I have used it a few times over the past year, but encountered an issue with installation. After following the instructions, testing the program leads to the following error 

> Traceback (most recent call last):
>   File "/home/biolinux/phage_programs/PhaBOX/main.py", line 33, in <module>
>     from scripts.data import load_data, preprocess_features, preprocess_adj, sample_mask
>   File "/home/biolinux/phage_programs/PhaBOX/scripts/data.py", line 5, in <module>
>     from    scipy.sparse.linalg.eigen.arpack import eigsh
> ModuleNotFoundError: No module named 'scipy.sparse.linalg.eigen.arpack'; 'scipy.sparse.linalg.eigen' is not a package

Help would be appreciated. I could not resolve this by installing different versions of scipy, as there were dependency conflicts.

**Comment by KennthShang** [comment]
Thanks for reporting the problem. We set a release to fix this installation problem. Please check the **release** to download the beta version codes. In this version, we updated the package names used in PhaBOX so it can be run correctly.

![image](https://github.com/KennthShang/PhaBOX/assets/22445402/d904726d-6ee2-4a3a-8e85-81c55a419090)


Best,
Jiayu

**Comment by sulmanm1** [comment]
Thank you! I will give it a try.
