### ISSUE TITLE
Can this tool be directly installed through conda?

### ISSUE THREAD

**Issue by iquasere** [KennthShang/PhaBOX#18]
Hello,

I am interested in using this tool, and integrating it in a snakemake pipeline. However, the [steps](https://github.com/KennthShang/PhaBOX?tab=readme-ov-file#prepare-the-database-and-environment) detailed in the README complicate the integration of the tool, since the paths have to be known before hand, and the name of the environment will be unpredictable (since it is a conda environment created by snakemake).

I want to know if it is possible to install this tool through something like `conda install phabox`. If not, can it be installed through `pip`?

**Comment by KennthShang** [comment]
I think you refer to the part of moving "blastxml_to_tabular.py" to the conda env?

Sorry for the confusion. We just forgot to remove that description, and it is useless for the current version by using the --script option. For the installation, you only need to run`conda env create -f webserver.yml -n phabox` once.

BTW, We will consider the binary usage installation in the near further and update the program soon. Thanks.

Best,
Jiayu

**Comment by joao1980** [comment]
Hi, I would also be interested in having a conda package ready to go for the tool. :)
In my case I am using nextflow.
Best,
Joao

**Comment by KennthShang** [comment]
Hi there,

We have made an update and the packages can be installed via:

```
conda create -n PhaBOX phabox=1.1 -c bioconda -c conda-forage -c pytorch -c jyshang2

```
Or 

```
conda create -n ENV_NAME python=3.9.7
conda activate ENV_NAME
conda install phabox=1.1 -c bioconda -c conda-forage -c pytorch -c jyshang2
```

Best,
Jiayu

**Comment by KennthShang** [comment]
Hi there,

The PhaBOX is upgraded to a 2.0 version with more powerful usage. Besides, it can handle all kinds of viruses now. Feel free to check!

Best,
Jiayu
