### ISSUE TITLE
print(f'Database directory {db_dir} missing or unreadable')

### ISSUE THREAD

**Issue by 2061574124** [KennthShang/PhaBOX#19]
firstly, i run: **git clone https://github.com/KennthShang/PhaBOX.git**
and then, 
**cd PhaBOX/
conda env create -f webserver.yml -n phabox
conda activate phabox**

download the **database.zip and parameters.zip** to the PhaBOX folder with baidu cloud.

and run: 
**unzip phagesuite_database.zip  > /dev/null
unzip phagesuite_parameters.zip  > /dev/null**

after that i make a test;
python PhaMer_single.py --contigs test_contigs.fa --threads 8 --len 3000 --rootpth simple_test --out out/ --dbdir database/ --parampth parameters/ --scriptpth scripts/
  File "PhaMer_single.py", line 65
    **print(f'Database directory {db_dir} missing or unreadable')**
                                                             ^
SyntaxError: invalid syntax

**I don't know that it was caused by my operation error in that step. I am looking forward to your reply very much**

**Comment by KennthShang** [comment]
Hi, 

it seems the 'database' folder is not exist under our PhaBOX path. 

Can you check whether the zip files are unzipped correctly? 
try
```
unzip phagesuite_database.zip
unzip phagesuite_parameters.zip 


```

You can also attach a screenshot for all the files within your PhaBOX

Best,
Jiayu

**Comment by 2061574124** [comment]
> Hi,
> 
> it seems the 'database' folder is not exist under our PhaBOX path.
> 
> Can you check whether the zip files are unzipped correctly? try
> 
> ```
> unzip phagesuite_database.zip
> unzip phagesuite_parameters.zip 
> ```
> 
> You can also attach a screenshot for all the files within your PhaBOX
> 
> Best, Jiayu

![2024-07-10 14-45-46屏幕截图](https://github.com/KennthShang/PhaBOX/assets/142213348/cf3f6061-af1b-4a72-b254-c9af77e88e40)
Thanks so much！ABOVE IS THE SCREENSHOT FOR ALL FILES WITHIN PhaBOX

**Comment by KennthShang** [comment]
I suddenly found your error message is SyntaxError: invalid syntax

which means there should be a problem with your environment. Can you show the terminal you run the codes?

Best,
Jiayu

**Comment by KennthShang** [comment]
And this error usually happen when you python is 2 but the phabox env should be 3

**Comment by 2061574124** [comment]
> And this error usually occurs when your python is 2, but the phabox env should be 3

Thank you very much for your patient. It is true that python2 was used before. I directly conda install python=3.8 in phabox environment. However, the following error occurs when i run following code：
![2024-07-10 17-42-23屏幕截图](https://github.com/KennthShang/PhaBOX/assets/142213348/91c0c0a1-342e-4f78-a18e-16594b50c3ce)

**Comment by 2061574124** [comment]
> > And this error usually occurs when your python is 2, but the phabox env should be 3
> 
> Thank you very much for your patient. It is true that python2 was used before. I directly conda install python=3.8 in phabox environment. However, the following error occurs when i run following code： ![2024-07-10 17-42-23屏幕截图](https://private-user-images.githubusercontent.com/142213348/347351298-91c0c0a1-342e-4f78-a18e-16594b50c3ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MDUxNDMsIm5iZiI6MTcyMDYwNDg0MywicGF0aCI6Ii8xNDIyMTMzNDgvMzQ3MzUxMjk4LTkxYzBjMGExLTM0MmUtNGY3OC1hMThlLTE2NTk0YjUwYzNjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQwOTQ3MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGFiNjhmNmZkYTAyMTllNzliMjVmMmJkY2I0NjAzYzI0NTU4MjQxZDY4YzA4MGIyMzFkMmJkMzIzYzI1YTYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YmbBLJTGsIOqTWVFoABA7c5G8BSOJlcrOLKe5Fd4z8E)

**Comment by KennthShang** [comment]
This should be a problem caused by your personal computer, because when running `conda env create -f webserver.yml -n phabox`, it will only install the python3.

There are several steps maybe you can try:

1. Please try to remove or uninstall the python2 in your env PATH
2. Please try to install anaconda/miniconda with python3 default.
3. Reinstall phabox using `conda env create -f webserver.yml -n phabox`

Hope this will help.

If you still cannot solve the problem, please try our webserver [PhaBOX](https://phage.ee.cityu.edu.hk/)

Best,
Jiayu
