### ISSUE TITLE
Taxonomy classification: PhaGCN 2.0 vs PhaBOX

### ISSUE THREAD

**Issue by JialinHe0o0** [KennthShang/PhaBOX#20]
Hi,
Thank you so much for creating such a great tool! 
When I was doing phage taxonomy classification, I got different results with `PhaGCN2.0` vs. `PhaBOX's PhaGCN`. Your article suggests that `PhaGCN 2.0` has higher accuracy than the previous version. 
So would you recommended to use `PhaGCN2.0` for classification and other tools in `PhaBOX` for host prediction etc?
Thank you!

**Comment by JialinHe0o0** [comment]
> If you only want to predict the taxonomy for phages, you can go through and use all the tools in the PhaBOX. The programs are continuously maintained and we have already updated the PhaGCN in PhaBOX to have the latest best performance. ( However, we cannot update the published paper to inform the users
> 
> But If you want to predict taxonomy for other viruses, you should go for PhaGCN 2.0. The PhaGCN in PhaBOX only consider the phages sequences in your data.
> 
> Best, Jiayu

Thank you so much for replying so quickly! It helped me a lot! Best wishes for your work~

**Comment by KennthShang** [comment]
Hi there,

The PhaBOX is upgraded to a 2.0 version with more powerful usage. Besides, it can handle all kinds of viruses now. Feel free to check!

Best,
Jiayu
