### ISSUE TITLE
Clarification on "Unknown" vs. "No Family Available" in Phagcn Taxonomy Predictions

### ISSUE THREAD

**Issue by F4NG666** [KennthShang/PhaBOX#23]
Hi,
I hope you are doing well. 
I am using the Phabox software with the Phagcn module for taxonomy classification predictions. In the output, I encounter two specific terms in the results: "unknown" and "no family available."

Could you please explain the difference between these two terms? 

best regards
Fang

**Comment by KennthShang** [comment]
Hi there,

The difference is: 

"unknown": probably a 'new' phages
"no family available": probably a known phage but latest ICTV do not assign a family level name


Best,
Jiayu

**Comment by KennthShang** [comment]
Hi there,

Out PhaBOX has upgraded into 2.0 version. The taxonomy will provide more detailed information with the latest ICTV2024. In addition, it can handle all the viruses now. Please check.

Best,
Jiayu
