### ISSUE TITLE
Error in Bio.Application and how to build better command line with the subprocess module

### ISSUE THREAD

**Issue by XuyingZhu** [KennthShang/PhaBOX#24]
Dear PhaBox team,
Thanks for such an amazing tool. However, I had a problem when testing four functions of PhaBox. I was suggested to build a command line with the subprocess module. Would you please give some advice on the new command or other ways to solve this problem? Thank you, and I am looking forward to your recent reply! 
My commands are:
export PATH=$PATH:/share/home/zhuyy/software/PhaBOX-main
# run PhaMer
python /share/home/zhuyy/software/PhaBOX-main/PhaMer_single.py --contigs /share/home/zhuyy/software/PhaBOX-main/test_contigs.fa --threads 48 --len 3000 --rootpth simple_test --out PhaMer_out/ --dbdir database/ --parampth parameters/ --scriptpth scripts/
# run PhaTYP
python /share/home/zhuyy/software/PhaBOX-main/PhaTYP_single.py --contigs /share/home/zhuyy/software/PhaBOX-main/test_contigs.fa --threads 48 --len 3000 --rootpth simple_test --out PhaTYP_out/ --dbdir database/ --parampth parameters/ --scriptpth scripts/
# run PhaGCN
python /share/home/zhuyy/software/PhaBOX-main/PhaGCN_single.py --contigs /share/home/zhuyy/software/PhaBOX-main/test_contigs.fa --threads 48 --len 3000 --rootpth simple_test --out PhaGCN_out/ --dbdir database/ --parampth parameters/ --scriptpth scripts/
# run CHERRY
python /share/home/zhuyy/software/PhaBOX-main/Cherry_single.py --contigs /share/home/zhuyy/software/PhaBOX-main/test_contigs.fa --threads 48 --len 3000 --rootpth simple_test --out Cherry_out/ --dbdir database/ --parampth parameters/ --scriptpth scripts/

And the error message is as follows:
/share/home/zhuyy/anaconda3/lib/python3.11/site-packages/Bio/Application/__init__.py:40: BiopythonDeprecationWarning: The Bio.Application modules and modules relying on it have been deprecated.

Due to the on going maintenance burden of keeping command line application
wrappers up to date, we have decided to deprecate and eventually remove these
modules.

We instead now recommend building your command line and invoking it directly
with the subprocess module.

Best wishes,
Xuying Zhu

**Comment by KennthShang** [comment]
Hi there,

This is just a warning message and you do not need to do anything. The program can be run correctly.

If you want to remove warning message, you can downgrade your python environment or reinstall it using 

    conda create -n PhaBOX phabox=1.1 -c bioconda -c conda-forge -c pytorch -c jyshang2

Best,
Jiayu

**Comment by XuyingZhu** [comment]
Hi Jiayu,
Thank you for your reply. I have reinstalled it and run the program successfully. 
Best wishes,
Xuying Zhu

**Comment by KennthShang** [comment]
Hi Xuying,

Our PhaBOX has been upgraded into 2.0 version with more powerful usage. Please check the guidelines!

Best,
Jiayu

**Comment by XuyingZhu** [comment]
Hi Jiayu,

Thank you for telling me the updated information. I will keep using this useful tool!

Best wishes,
Xuying Zhu

**Comment by XuyingZhu** [comment]
Hi Jiayu,

Thank you for telling me the updated information. I will keep using this helpful tool!

Best wishes,
Xuying Zhu
