### ISSUE TITLE
Add shebang line

### ISSUE THREAD

**Issue by bernt-matthias** [KennthShang/PhaBOX#26]
Could you add a shebang line to all python scripts, i.e. use `#!/usr/bin/env python` as first line. The advantage would be that the scripts can be executed directly. 

Maybe you could also consider to add `entry_points` (https://setuptools.pypa.io/en/latest/userguide/entry_point.html) to your setup.py. Then they would be installed to the `PATH` when installed with `pip`.

**Comment by KennthShang** [comment]
Good to know.

The ```#!/usr/bin/env python``` is added to the scripts.

Currently, I am adjusting the scripts in PhaBOX (upgrading the program and adding new functions). If you have further suggestions, please let me know. Thanks a lot.

Best,
Jiayu

**Comment by KennthShang** [comment]
I am glad to tell you that the phabox has been upgraded to the 2.0 version.

I also provided the meta.yaml and the pyproject.toml for you reference. Hope it will help.

Best,
Jiayu
