### ISSUE TITLE
PhaBOX not installable via conda

### ISSUE THREAD

**Issue by pmaen** [KennthShang/PhaBOX#30]
When running 
```
conda create -n phabox2 jyshang2::phabox=2.1 -c bioconda -c conda-forge -y
```
like specified in the wiki, the following output and error is shown:
```
Channels:
 - bioconda
 - conda-forge
 - defaults
 - jyshang2
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package phabox-2.1.0-pypy_0 is excluded by strict repo priority
```

This is happening on Ubuntu 24.04.1 LTS with conda version 24.9.1 (miniconda3).

**Comment by stxso22** [comment]
I was having the same issue but found that running this instead worked:

`conda create -n phabox2 jyshang2::phabox -c bioconda -c conda-forge -y`

I followed the rest of the steps at: https://github.com/KennthShang/PhaBOX/wiki 

But I had to downgrade to numpy 1.26.4 to get it to run

**Comment by KennthShang** [comment]
Hi everyone,

I finally repeated the problem and found the bug. This is because the current package is built based on a system with the latest GPU setting. Please use the following codes as a temporary way to install phabox2. The problem will be fixed within today and let you know as soon as possible:

```
conda create --name phabox2 python=3.10
onda activate phabox2
conda install diamond=0.9.14 blast=2.16.0 mcl fasttree=2.1.11 kcounter=0.1.1 mafft=7.525
conda install numpy=1.26.4 pandas=2.2.3 networkx=3.4.2 seaborn-base=0.13.2 biopython=1.84 tqdm=4.66.5 scipy=1.14.1
conda install datasets transformers pytorch triton accelerate prodigal-gv


git clone https://github.com/KennthShang/PhaBOX.git
cd PhaBOX
python  -m pip install . -vv
```
Best,
Jiayu

**Comment by KennthShang** [comment]
The `phabox2.yaml` is also updated.

Best,
Jiayu

**Comment by ShuqingL** [comment]
Hi @KennthShang
Which version of Python can I use to install PhaBOX2?
