### ISSUE TITLE
Minor problems in the output docs

### ISSUE THREAD

**Issue by bernt-matthias** [KennthShang/PhaBOX#42]
The description of the PhaGCN output in the wiki misses two columns

- Host_NCBI_lineage
- Host_GTDB_lineage

The listed order of the columns for vOTU grouping is wrong.

**Comment by KennthShang** [comment]
Thanks for catching this. The two missing columns belong to the CHERRY's output and were added in [wiki](https://github.com/KennthShang/PhaBOX/wiki/Outputs#cherry)

I found that the AAI-based order is different from the ANI-based. I have fixed the problem and will release new versions after summarizing all the updates.
