### ISSUE TITLE
PhaBox2 Conda Installation Error (+Solution)

### ISSUE THREAD

**Issue by erfanshekarriz** [KennthShang/PhaBOX#43]
Dear JiaYu, 

I wanted to report a small channel priority issue for conda installation of PhaBox2 that I've managed to fix. I would recommend updating your Wiki!

This installation works: 
```bash 
conda create -n phabox2 phabox=2.1.5 -c conda-forge -c bioconda -y
```

This installation gives an error: 
```bash
conda create -n phabox2 phabox=2.1.5 -c bioconda -c conda-forge -y
````

The `-c conda-forge` repository needs to be set at top priority and `-c bioconda` as second priority. This wouldn't raise an error if  `conda config --set channel_priority flexible` is set, but for me I always have my configuration on `conda config --set channel_priority strict` to make sure all environments are reproducible. 

#### Final Solution, run:

```bash
conda config --add channels bioconda
conda config --add channels conda-forge
conda config --set channel_priority strict
conda create -n phabox2 phabox=2.1.5 -c conda-forge -c bioconda -y
```

Hope this helps! I wanted to post it here incase someone runs into a similar issue. 

Best,
Erfan

**Comment by KennthShang** [comment]
I see. Good to know.

I will revise the WIKI accordingly. Thanks.

Best,
Jiayu
