### ISSUE TITLE
Documentation Typo "hypothetical protein (no hit)" PhaVIP

### ISSUE THREAD

**Issue by erfanshekarriz** [KennthShang/PhaBOX#44]
Hi Jiayu, 

Just a small typo in the documentation for [PhaVIP](https://github.com/KennthShang/PhaBOX/wiki/Outputs#-phavip-annotation):

```
Please note that there are two kinds of hypothetical protein:

hypothetical protein (no hit): a protein has no alignment results to the reference database.
hypothetical protein (no hit): a protein has alignment results but the annotation is "hypothetical protein"
```

I think here you mean `hypothetical protein (no hit)` vs. `hypothetical protein`. I wanted to clarify. 

Thanks! 
Best, 

Erfan

**Comment by KennthShang** [comment]
Thanks for catching this Erfan! I revised it accordingly.

Best,
Jiayu
