### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by sulmanm1** [KennthShang/PhaBOX#7]
I ran PhaGCN_single.py on my contigs and received the prediction "Peduoviridae". I do not know of such a phage, is this supposed to be podoviridae?

**Comment by KennthShang** [comment]
Hi there,

This is the link for your concerns: https://viralzone.expasy.org/10340?outline=all_by_species

I guess you also want to know something about the latest ICTV: https://ictv.global/taxonomy

Best,
Jiayu
