### ISSUE TITLE
[improvement] adding blastxml_to_tabular.py as an input parameter to the main.py function. 

### ISSUE THREAD

**Issue by erfanshekarriz** [KennthShang/PhaBOX#8]
Hello!

In the installation instructions, you've mentioned moving blastxml_to_tabular.py to the conda environment. 

For streamlining the portability of phabox offline is it possible to be given as an input to the main.p/PhaMer_single.py files?

This would be super useful for people wanting to make their own custom pipelines from the PhaMer_single.py module!

Best, 

Erfan

**Comment by KennthShang** [comment]
Hi,

Thanks for your suggestion, The function has been added.

Best,
Jiayu

**Comment by erfanshekarriz** [comment]
> Hi,
> 
> 
> 
> Thanks for your suggestion, The function has been added.
> 
> 
> 
> Best,
> 
> Jiayu

Great! Thank you for the prompt reply and maintenance.

Best

Erfan

**Comment by erfanshekarriz** [comment]
> Hi,
> 
> Thanks for your suggestion, The function has been added.
> 
> Best, Jiayu

Hello 👋  

When running:
```
python pipeline/bin/PhaBOX/PhaMer_single.py  \
--contigs output/2__assembly/contigs/crAssphage.fa \
--threads 8 \
--len 100 \
--rootpth tmp \
--dbdir pipeline/database/phabox/ \
--parampth pipeline/params/phabox/
````
I get the following error:
```
Traceback (most recent call last):
  File "/path/to/PhaBOX/PhaMer_single.py", line 101, in <module>
    convert_xml(os.path.join(rootpth, midfolder), 'phamer', scriptpth)
NameError: name 'scriptpth' is not defined
```

Looking at your commit history I'm assuming  you've added scrptpath as an input to main.py but not to singular files. In my case I would only be interested in the PhaMer_single.py.

Best, 

Erfan

**Comment by KennthShang** [comment]
Yeah, sorry about that. The '--scriptpth' has been added to all the scripts now.

Best,
Jiayu

**Comment by erfanshekarriz** [comment]
Hi Jiayu, 

Great. Thanks a lot. I've tested it out and it works perfectly fine so on that note I will close this thread!

thanks again
