### ISSUE TITLE
Conda [/Mamba] Installation Channel Priority Strict Error

### ISSUE THREAD

**Issue by erfanshekarriz** [KennthShang/PhaBOX#9]
Hello and hope all is well. 

I wanted to report that the conda installation only works when setting channel priorities as flexible ```conda config --set channel_priority flexible```, but does not work when set to ```strict```. 

This can be a huge future problem with reproducibility since the flexible mode can arbitrarily take any version of any software from the channels you've set (and you have around 6 set which is also lots to handle). 

I found out about this problem when failing to install PhaBox on a second server without noticing that my original server was accidentally set to ```flexible``` mode while the new server was correctly set to ```strict```.

I would highly recommend seeing if a conda recipe with strict channel priorities can be set as with flexible mode there is no guarantee of reproducibility [even for yourself] on different systems, which doesn't go well with the fact that conda recipes are usually made for reproducibility.

For anyone struggling with installations, I recommend  running ```conda config --set channel_priority flexible``` and then back to ```conda config --set channel_priority strict``` upon installation. 

I've attached a sample error file to see the conflicts it causes. 
[error.txt](https://github.com/KennthShang/PhaBOX/files/13500072/error.txt)

Hope this helps. 

Best, 

Erfan

**Comment by KennthShang** [comment]
Hi there,

The PhaBOX is upgraded to a 2.0 version with more powerful usage. Besides, it can be installed without the yaml file. So the channel priority problem is fixed.

Best,
Jiayu
